Resources:
  DatascienceSvcBuildOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DatascienceSvcBuildOnly-*:log-stream:*
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'
  DatascienceSvcDeployDevRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DatascienceSvcDeployDev-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/dev/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/dev/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DatascienceSvcDeployStagingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DatascienceSvcDeployStaging-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/staging/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/staging/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DatascienceSvcDeployQARole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DatascienceSvcDeployQA-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/qa/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/qa/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DatascienceSvcDeployProdRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DatascienceSvcDeployProd-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DatascienceSvcDeployProdUSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DatascienceSvcDeployProdUS-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_us/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_us/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DatascienceSvcDeployProdCARole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DatascienceSvcDeployProdCA-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_ca/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_ca/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'
