Resources:
  DataStreamSvcBuildOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DataStreamSvcBuildOnly-*:log-stream:*
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DataStreamSvcDeployDevRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DataStreamSvcDeployDev-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/dev/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/dev/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DataStreamSvcDeployStagingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DataStreamSvcDeployStaging-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/staging/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/staging/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DataStreamSvcDeployQARole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DataStreamSvcDeployQA-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/qa/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/qa/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DataStreamSvcDeployProdRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DataStreamSvcDeployProd-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DataStreamSvcDeployProdUSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DataStreamSvcDeployProdUS-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_us/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_us/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  DataStreamSvcDeployProdCARole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/DataStreamSvcDeployProdCA-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_ca/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_ca/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'
