Resources:
  KDAFlinkSvcBuildOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/KDAFlinkSvcBuildOnly-*:log-stream:*
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  KDAFlinkSvcDeployDevRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/KDAFlinkSvcDeployDev-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/dev/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/dev/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  KDAFlinkSvcDeployStagingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/KDAFlinkSvcDeployStaging-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/staging/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/staging/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  KDAFlinkSvcDeployQARole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/KDAFlinkSvcDeployQA-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/qa/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/qa/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  KDAFlinkSvcDeployProdRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/KDAFlinkSvcDeployProd-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  KDAFlinkSvcDeployProdUSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/KDAFlinkSvcDeployProdUS-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_us/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_us/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'

  KDAFlinkSvcDeployProdCARole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: 'LogToCloudWatchAccess'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:/aws/codebuild/KDAFlinkSvcDeployProdCA-*:log-stream:*
              - Sid: 'ParameterStoreAccess'
                Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource:
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_ca/access-key-id
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/aws/prod_ca/secret-access-key
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-user
                  - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/infra/pipelines/docker/mysense-password
              - Sid: 'ListStackExports'
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource:
                  - '*'
